server:
  port: 8077

spring:
  application:
    name: e-library

repo:
  implementation: hibernate # Хотел включать реализацию repo На Hibernate в зависимости от этого значения через
  # @ConditionalOnProperty(prefix = "repo", value = "implementation", havingValue = "hibernate") невышло