server:
  port: 8077
  servlet:
    context-path: /e-library

spring:
  jpa:
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5477/postgres
    username: postgres
    password: qwerty
    driverClassName: org.postgresql.Driver

jwt:
  secret: Gennadiy good